mysite/enquetes/urls.py
from django.urls import path
from . import views

app_name = "enquetes"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('principal.urls')),
    path('enquetes/', include('enquetes.urls')),
    path('simulado/', include('simulado.urls')),
    path('admin/', admin.site.urls),
]

mysite/enquetes/models.py
import datetime
from operator import truediv

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pubdate = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pubdate >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'datapub'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Recente?'






class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/enquetes/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Choice, Question
from django.http import Http404




# Create your views here.
class IndexView(generic.ListView):
    template_name = "enquetes/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by("-pubdate")[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "enquetes/question_detail.html"

class ResultsView(generic.DetailView):
    model = Question
    template_name = "enquetes/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "enquetes/detail.html",{"question": question, "error_message": "Você não selecionou uma alternativa.",},)
    else:
            selected_choice.votes += 1
            selected_choice.save()
            return HttpResponseRedirect(reverse("enquetes:results", args=(question.id,)))

mysite/enquetes/templates/enquetes/detail.html
<!DOCTYPE html>
<html lang="en">
<head></head>
<body>
<form action="{% url 'enquetes:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>
</body>

</html>

mysite/enquetes/templates/enquetes/index.html
<!DOCTYPE html>
<html lang="en">
<head></head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'enquetes:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>

</html>

mysite/enquetes/templates/enquetes/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head></head>
<body>
<form action="{% url 'enquetes:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>
</body>

</html>

mysite/enquetes/templates/enquetes/results.html
<!DOCTYPE html>
<html lang="en">
<head></head>
<body>
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'enquetes:detail' question.id %}">Votar novamente?</a>
</body>

</html>