mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('principal.urls')),
    path('enquetes/', include('enquetes.urls')),
    path('simulado/', include('simulado.urls')),
    path('admin/', admin.site.urls),
]

mysite/simulado/urls.py
from django.urls import path
from . import views

app_name = 'simulado'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('cadastro/', views.CadastrarEstudanteView.as_view(), name='registrar'),
    path('login/', views.login_usuarioView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('simulados/', views.ListarSimuladosView.as_view(), name='listar_simulados'),
    path('detalhar/<int:pk>/', views.DetalharSimuladosView.as_view(), name='detalhar_simulado'),
    path('adicionar/questao/', views.AdicionarQuestaoView.as_view(), name='adicionar_questao'),
    path('adicionar/simulado/', views.AdicionarSimuladoView.as_view(), name='adicionar_simulado'),
]

mysite/simulado/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

# Create your models here.


def pontuacao_certa(value):
    if (value < 0 or value > 100):
        raise ValidationError(str(value) + " não é um valor adequado. Por favor, selecione um número entre 0 e 100")

class Tema(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self):
        return self.nome

class Questao(models.Model):
    enunciado = models.CharField("enunciado", max_length=200)
    pontuacao = models.PositiveIntegerField(default=0, validators=[pontuacao_certa])
    tema = models.ForeignKey(Tema, on_delete=models.SET_DEFAULT, default=3)

    def __str__(self):
        return self.enunciado


class Simulado(models.Model):
    nome = models.CharField(max_length=100)
    data_criacao = models.DateTimeField("data criada")
    tema = models.ForeignKey(Tema, on_delete=models.SET_NULL, null=True)
    questao = models.ManyToManyField(Questao)

    def __str__(self):
        return self.nome

class Alternativa(models.Model):
    alternativa_texto = models.CharField(max_length=200)
    alternativa_correta = models.BooleanField(default=False)
    questao = models.ForeignKey(Questao, on_delete=models.CASCADE)

    def __str__(self):
        return self.alternativa_texto

class Estudante(models.Model):
    tema_favorito = models.ForeignKey(Tema, on_delete=models.SET_NULL, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

mysite/simulado/views.py
from typing import Any, Dict
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from .models import Estudante, Tema, Alternativa, Simulado, Questao
from django.db.models import Sum
import datetime





# Create your views here.
class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'simulado/index.html')


class ListarSimuladosView(View):
    def get(self, request, *args, **kwargs):
        simulados = Simulado.objects.all()
        termo_pesquisa = request.GET.get('q', None)

        if termo_pesquisa:
            simulados = simulados.filter(nome__icontains=termo_pesquisa)
        return render(request, 'simulado/listar_simulados.html', {'simulados': simulados})

class CadastrarEstudanteView(View):
    def get(self, request, *args, **kwargs):
        tema_favorito_select = Tema.objects.all()
        return render(request, 'simulado/cadastro.html', {'tema_favorito_select': tema_favorito_select})
    
    def post(self, request, *args, **kwargs):
        estudante_form = {
            'tema_favorito': request.POST['tema_favorito'],
        }
        tema_favorito_select = Tema.nome.field.choices

        estudante_form['tema_favorito'] = Tema.objects.get(pk=estudante_form['tema_favorito'])

        user_form = {
            'username': request.POST['username'],
            'password': request.POST['password'],
            'email': request.POST['email'],
        }

        if User.objects.filter(username=user_form['username']):
            contexto = {
                'error': {'field':'username', 'message': 'Nome de usuário já está em uso"'},
                'estudante_form': estudante_form,
                'user_form': user_form
            }
            return render(request, 'simulado/cadastro.html', contexto)

        if User.objects.filter(email=user_form['email']):
            contexto = {
                'error': {'field':'email', 'message': 'Email já está em uso'},
                'estudante_form': estudante_form,
                'user_form': user_form
            }
            return render(request, 'simulado/cadastro.html', contexto)
    
        user = User.objects.create_user(
            username=user_form['username'], email=user_form['email'], password=user_form['password']
            )
        
        if not user:
            return render(request, 'simulado/erro.html')
        
        novo_estudante = Estudante(**estudante_form, user=user)

        novo_estudante.save()

        login(request, user)

        return render(request, 'simulado/index.html', {'estudante': novo_estudante})




class login_usuarioView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'simulado/login.html')
    
    def post(self, request, *args, **kwargs):
        login_form = {
            'username': request.POST['username'],
            'password': request.POST['password'],
        }

        user = authenticate(request, **login_form)

        if user is not None:
            login(request, user)
            return redirect(reverse('simulado:index'))
        
        context = {
            'login_form': login_form,
            'error': {
                'message': "Credenciais inválidas."
            }
        }

        print(context)
        return render(request, 'simulado/login.html', context)

class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return render(request, 'simulado/index.html')

class AdicionarQuestaoView(View):
    @method_decorator(login_required(login_url='/simulado/login', redirect_field_name=None))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        tema_select = Tema.objects.all()
        return render(request, 'simulado/adicionar_questao.html', {'tema_select':tema_select})
    
    def post(self, request, *args, **kwargs):
        questao_form = {
            'enunciado': request.POST['enunciado'],
            'pontuacao': request.POST['pontuacao'],
            'tema': request.POST['tema'],
        }
        tema_select = Tema.nome.field.choices

        questao_form['tema'] = Tema.objects.get(pk=questao_form['tema'])

        questao = Questao.objects.create(**questao_form)
        for i in range(1, 5):
            alternativa_texto = request.POST.get(f'alternativa_texto_{i}', None)
            alternativa_correta = request.POST.get(f'alternativa_correta', None)

            if alternativa_texto and alternativa_correta and int(alternativa_correta) == i:
                Alternativa.objects.create(alternativa_texto=alternativa_texto, alternativa_correta=True, questao=questao)
            else:
                Alternativa.objects.create(alternativa_texto=alternativa_texto, alternativa_correta=False, questao=questao)


        return redirect(reverse('simulado:index'))


class AdicionarSimuladoView(View):
    @method_decorator(login_required(login_url='/simulado/login', redirect_field_name=None))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    def get(self, request, *args, **kwargs):
        tema_select = Tema.objects.all()
        questoes_disponiveis = Questao.objects.all()
        return render(request, 'simulado/adicionar_simulado.html', {'tema_select':tema_select, 'questoes_disponiveis':questoes_disponiveis})
    
    def get(self, request, *args, **kwargs):
        tema_select = Tema.objects.all()
        questoes_disponiveis = Questao.objects.all()
        return render(request, 'simulado/adicionar_simulado.html', {'tema_select': tema_select, 'questoes_disponiveis': questoes_disponiveis})
    
    def post(self, request, *args, **kwargs):
        nome = request.POST['nome']
        data_criacao = request.POST['data_criacao']
        tema_id = request.POST['tema']
        questoes_selecionadas = request.POST.getlist('questoes[]')

        tema = Tema.objects.get(pk=tema_id)

        # Inicializa a nota máxima com 0
        nota_maxima = 0

        # Lista para armazenar as questões selecionadas com suas respectivas pontuações
        questoes_com_pontuacao = []

        for questao_id in questoes_selecionadas:
            questao = Questao.objects.get(pk=questao_id)
            pontuacao = request.POST.get(f'pontuacao_{questao_id}', 0)
            nota_maxima += int(pontuacao)  # Soma a pontuação da questão à nota máxima
            questoes_com_pontuacao.append((questao, pontuacao))

        # Cria o simulado com o tema selecionado
        simulado = Simulado.objects.create(nome=nome, data_criacao=data_criacao, tema=tema)

        # Adiciona as questões selecionadas ao simulado com suas pontuações personalizadas
        for questao, pontuacao in questoes_com_pontuacao:
            simulado.questao.add(questao, through_defaults={'pontuacao': pontuacao})

        # Salva a nota máxima no simulado
        simulado.nota_maxima = nota_maxima
        simulado.save()

        return redirect(reverse('simulado:index'))

class DetalharSimuladosView(View):
    template_name = 'simulado/detalhar_simulado.html'

    def get(self, request, *args, **kwargs):
        # Obtém o simulado a partir do ID na URL
        simulado_id = self.kwargs.get('pk')
        simulado = Simulado.objects.get(pk=simulado_id)

        # Exibe o formulário com as questões e alternativas do simulado
        return render(request, self.template_name, {'simulado': simulado})

    def post(self, request, *args, **kwargs):
        # Obtém o simulado a partir do ID na URL
        simulado_id = self.kwargs.get('pk')
        simulado = Simulado.objects.get(pk=simulado_id)

        # Inicializa variáveis para armazenar as respostas do usuário
        respostas_corretas = 0
        nota_obtida = 0

        # Processa as respostas do usuário
        for questao in simulado.questao.all():
            alternativa_id = request.POST.get(f'questao_{questao.id}', None)
            if alternativa_id:
                alternativa = Alternativa.objects.get(pk=alternativa_id)
                if alternativa.alternativa_correta:
                    respostas_corretas += 1
                    nota_obtida += questao.pontuacao

        # Calcula a nota máxima do simulado somando a pontuação de todas as questões
        nota_maxima = simulado.questao.aggregate(Sum('pontuacao'))['pontuacao__sum']

        # Calcula a porcentagem de acertos
        porcentagem_acertos = (respostas_corretas / simulado.questao.count()) * 100

        # Exibe o resultado com as respostas do usuário, as respostas corretas e a nota obtida
        return render(request, self.template_name, {
            'simulado': simulado,
            'respostas_corretas': respostas_corretas,
            'nota_obtida': nota_obtida,
            'nota_maxima': nota_maxima,
            'porcentagem_acertos': porcentagem_acertos,
        })
    #for i in range(1, 5):
    #        alternativa_texto = request.POST.get(f'alternativa_texto_{i}', None)
    #        alternativa_correta = request.POST.get(f'alternativa_correta', None)#
    #
    #        if alternativa_texto and alternativa_correta and int(alternativa_correta) == i:
    #            Alternativa.objects.create(alternativa_texto=alternativa_texto, alternativa_correta=True, questao=questao)
    ##        else:
    #            Alternativa.objects.create(alternativa_texto=alternativa_texto, alternativa_correta=False, questao=questao)

mysite/simulado/templates/simulado/adicionar_questao.html
<h1>Cadastro</h1>

<div>
    <h1 class="m-auto py-5 text-center d-flex flex-column">
      <b>Formulário de cadastro de questão</b>
    </h1>
    <div class="row justify-content-center">
      <div class="col-6">
        <form
          class="needs-validation"
          action="{% url 'simulado:adicionar_questao' %}"
          method="POST"
          enctype="multipart/form-data">
          {%csrf_token%}
          <h4>Crie uma questão</h4>
          <div class="row g-3">
            <div class="col-sm-12">
              <label
                for="enunciado"
                class="form-label"
                >Enunciado da questão</label
              >
              <div class="input-group">
                <input
                  type="text"
                  class="form-control {% if error.field == 'enunciado' %} is-invalid {% endif %}"
                  id="enunciado"
                  name="enunciado"
                  value="{{questao_form.enunciado}}"
                  placeholder="Qual é...?"
                  required />
                <div class="invalid-feedback">{{error.message}}</div>
              </div>
            </div>
  
            <div class="col-6">
              <label
                for="pontuacao"
                class="form-label"
                >Pontuação
              </label>
              <input
                type="text"
                class="form-control"
                id="pontuacao"
                name="pontuacao"
                value="{{questao_form.pontuacao}}"
                placeholder="10" />
            </div>
          </div>
          <div class="row g-3">

            <div class="col-6">
                <label
                  for="tema"
                  class="form-label"
                  >Tema</label
                >
                <select
                  class="form-select"
                  id="tema"
                  name="tema"
                  value="{{questao_form.tema}}"
                  
                  >
                    <option value="">Escolha...</option>
                    {% for tema in tema_select %}
                    <option value="{{ tema.id }}" {% if questao_form.tema == tema.id %}selected{% endif %}>{{ tema.nome }}</option>
                    {% endfor %}
                </select>
                <br>
                <br>
  
  
                <label for="alternativa_texto_1">Alternativa 1:</label>
                <input type="text" name="alternativa_texto_1" required>
                <input type="radio" name="alternativa_correta" value="1"> Correta
                <br>
                <label for="alternativa_texto_2">Alternativa 2:</label>
                <input type="text" name="alternativa_texto_2" required>
                <input type="radio" name="alternativa_correta" value="2"> Correta
                <br>
                <label for="alternativa_texto_3">Alternativa 3:</label>
                <input type="text" name="alternativa_texto_3" required>
                <input type="radio" name="alternativa_correta" value="3"> Correta
                <br>
                <label for="alternativa_texto_4">Alternativa 4:</label>
                <input type="text" name="alternativa_texto_4" required>
                <input type="radio" name="alternativa_correta" value="4"> Correta
                <br>
    <br>
    <input type="submit" value="Adicionar Questão e Alternativas">
        </form>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  

mysite/simulado/templates/simulado/adicionar_simulado.html
<h1>Criação de simulado</h1>
<form method="post">
    {% csrf_token %}
    <label for="nome">Nome do Simulado:</label>
    <input type="text" name="nome" required>
    <br>
    <label for="data_criacao">Data de Criação:</label>
    <input type="date" name="data_criacao" required>
    <br>
    <label for="tema">Tema:</label>
    <select name="tema" required>
        {% for tema in tema_select %}
            <option value="{{ tema.id }}">{{ tema.nome }}</option>
        {% endfor %}
    </select>
    <br>
    <br>
    <h3>Questões Disponíveis:</h3>
    <ul>
        {% for questao in questoes_disponiveis %}
            <li>
                <input type="checkbox" name="questoes[]" value="{{ questao.id }}">
                {{ questao.enunciado }} - Pontuação:
                <input type="number" name="pontuacao_{{ questao.id }}" value="{{ questao.pontuacao }}">
            </li>
        {% endfor %}
    </ul>
    <br>
    <input type="submit" value="Adicionar Simulado">
</form>

mysite/simulado/templates/simulado/cadastro.html
<h1>Cadastro</h1>

<div>
    <h1 class="m-auto py-5 text-center d-flex flex-column">
      <b>Formulário de cadastro</b>
    </h1>
    <div class="row justify-content-center">
      <div class="col-6">
        <form
          class="needs-validation"
          action="{% url 'simulado:registrar' %}"
          method="POST"
          enctype="multipart/form-data">
          {%csrf_token%}
          <h4>Crie sua conta</h4>
          <div class="row g-3">
            <div class="col-sm-12">
              <label
                for="username"
                class="form-label"
                >Nome de Usuário</label
              >
              <div class="input-group">
                <input
                  type="text"
                  class="form-control {% if error.field == 'username' %} is-invalid {% endif %}"
                  id="username"
                  name="username"
                  value="{{user_form.username}}"
                  placeholder="bruno2023"
                  required />
                <div class="invalid-feedback">{{error.message}}</div>
              </div>
            </div>
  
            <div class="col-6">
              <label
                for="password"
                class="form-label"
                >Senha
              </label>
              <input
                type="password"
                class="form-control"
                id="password"
                name="password"
                value="{{user_form.password}}"
                placeholder="******" />
            </div>
            <div class="col-6">
              <label
                for="password-confirmation"
                class="form-label"
                >Confirme sua senha
              </label>
              <input
                type="password"
                class="form-control"
                id="password-confirmation"
                name="password-confirmation"
                placeholder="******" />
            </div>
          </div>
          <hr class="my-4" />
          <h4>Sobre você</h4>
          <div class="row g-3">
  
            <div class="col-7">
              <label
                for="email"
                class="form-label"
                >E-mail</label
              >
              <div class="input-group">
                <input
                  type="email"
                  class="form-control {% if error.field == 'email' %} is-invalid {% endif %}"
                  id="email"
                  name="email"
                  value="{{user_form.email}}"
                  placeholder="seuemail@exemplo.com"
                  required />
                <div class="invalid-feedback">{{error.message}}</div>
              </div>
            </div>

            <div class="col-6">
                <label
                  for="tema_favorito"
                  class="form-label"
                  >Tema Favorito</label
                >
                <select
                  class="form-select"
                  id="tema_favorito"
                  name="tema_favorito"
                  value="{{estudante_form.tema_favorito}}"
                  
                  >
                    <option value="">Escolha...</option>
                    {% for tema in tema_favorito_select %}
                    <option value="{{ tema.id }}" {% if estudante_form.tema_favorito == tema.id %}selected{% endif %}>{{ tema.nome }}</option>
                    {% endfor %}
                </select>
                <div class="invalid-feedback">
                  Escolha seu tema favorito.
                </div>
  
  
          <hr class="my-4" />
  
          <button
            type="submit"
            class="btn btn-primary">
            Cadastrar
          </button>
        </form>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
  

mysite/simulado/templates/simulado/detalhar_simulado.html
<h1>Detalhes do Simulado</h1>

<p>Nome do Simulado: {{ simulado.nome }}</p>
<p>Data de Criação: {{ simulado.data_criacao }}</p>
<p>Tema: {{ simulado.tema }}</p>
<p>Nota máxima: {{ nota_maxima }}</p>

<h2>Questões do Simulado:</h2>
<form method="post" action="{% url 'simulado:detalhar_simulado' simulado.id %}">
  {% csrf_token %}
  {% for questao in simulado.questao.all %}
    <p>{{ questao.enunciado }}</p>
    {% for alternativa in questao.alternativa_set.all %}
      <input type="radio" name="questao_{{ questao.id }}" value="{{ alternativa.id }}">
      <label>{{ alternativa.alternativa_texto }}</label><br>
    {% endfor %}
  {% endfor %}
  <button type="submit">Enviar Respostas</button>
</form>

{% if respostas_corretas is not None %}
  <h2>Resultado:</h2>
  <p>Respostas Corretas: {{ respostas_corretas }}</p>
  <p>Nota Obtida: {{ nota_obtida }}</p>
  <p>Nota Máxima: {{ nota_maxima }}</p>
  <p>Porcentagem de Acertos: {{ porcentagem_acertos }}%</p>
{% endif %}

mysite/simulado/templates/simulado/index.html
<html>
    <head>
        <title>Simulado</title>
    </head>
    <body>
        <h1>Simulado Online</h1>
        <hr/>
        &copy; DSWeb/TADS/CNAT/IFRN 2023


      {% if user.is_authenticated %}
      
      <a
      href="{% url 'simulado:logout' %}"
      class="btn btn-outline-primary"
      >Logout</a
    >

    <a
      href="{% url 'simulado:adicionar_questao' %}"
      class="btn btn-outline-primary"
      >Adicionar questao</a
    >

    <a
      href="{% url 'simulado:adicionar_simulado' %}"
      class="btn btn-outline-primary"
      >Adicionar simulado</a
    >
      {% else %}
      <br>
        <a
        href="{% url 'simulado:registrar' %}"
        class="btn btn-outline-primary"
        >Cadastro</a
      >

        <a
        href="{% url 'simulado:login' %}"
        class="btn btn-outline-primary"
        >Login</a
      >

      <a
      href="{% url 'simulado:adicionar_questao' %}"
      class="btn btn-outline-primary"
      >Adicionar questao</a
    >
      {% endif %}
    </body>
</html>

mysite/simulado/templates/simulado/listar_simulados.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>SIMULADOS:</h1>

    <form method="get" action="{% url 'simulado:listar_simulados' %}">
        <input type="text" name="q" placeholder="Digite o termo de pesquisa">
        <input type="submit" value="Buscar">
    </form>

    <div>
        {% for simulado in simulados %}
        <a href="{% url 'simulado:detalhar_simulado' simulado.id %}">{{simulado.nome}}</a>
        <br>
        {% endfor %}
    </div>
</body>
</html>

mysite/simulado/templates/simulado/login.html
<div class="row justify-content-center">
    <div class="col-md-4">
      {% if error %}
      <div
        class="alert alert-danger mt-5"
        role="alert">
        {{error.message}}
      </div>
      {% endif %}
      <div class="card mt-{% if error %}2{%else%}5{% endif %}">
        <h3 class="text-center pt-4">Login</h3>
        <div class="card-body">
          <form
            action="{% url 'simulado:login' %}"
            method="POST">
            {%csrf_token%}
            <div class="mb-3">
              <label
                for="username"
                class="form-label"
                >Nome de Usuário</label
              >
              <div class="input-group">
                <input
                  type="text"
                  class="form-control {% if error %} is-invalid {% endif %}"
                  id="username"
                  name="username"
                  placeholder="Digite seu nome de usuário"
                  required />
              </div>
            </div>
  
            <div class="mb-3">
              <label
                for="password"
                class="form-label"
                >Senha</label
              >
              <input
                type="password"
                class="form-control {% if error %} is-invalid {% endif %}"
                id="password"
                name="password"
                placeholder="Digite sua senha" />
            </div>
            <div class="d-flex justify-content-between">
              <div class="col-6 g-2">
                <a
                  type="submit"
                  class="btn btn-outline-success w-100"
                  href="{% url 'simulado:registrar' %}">
                  Cadastre-se
                </a>
              </div>
              <div class="col-5">
                <button
                  type="submit"
                  class="btn btn-primary w-100">
                  Entrar
                </button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>