mysite/enquetes/urls.py
from django.urls import path
from . import views

app_name = "enquetes"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('principal.urls')),
    path('enquetes/', include('enquetes.urls')),
    path('simulado/', include('simulado.urls')),
    path('admin/', admin.site.urls),
]

mysite/principal/urls.py
from django.urls import path
from . import views

app_name = 'principal'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
]

mysite/simulado/urls.py
from django.urls import path
from . import views

app_name = 'simulado'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('cadastro/', views.CadastrarEstudanteView.as_view(), name='registrar'),
    path('login/', views.login_usuarioView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('simulados/', views.ListarSimuladosView.as_view(), name='listar_simulados'),
    path('detalhar/<int:pk>/', views.DetalharSimuladosView.as_view(), name='detalhar_simulado'),
    path('adicionar/questao/', views.AdicionarQuestaoView.as_view(), name='adicionar_questao'),
    path('adicionar/simulado/', views.AdicionarSimuladoView.as_view(), name='adicionar_simulado'),
]

mysite/principal/models.py
from django.db import models

# Create your models here.

mysite/principal/views.py
from django.shortcuts import render
from django.views import View


# Create your views here.
class IndexView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'principal/index.html')

mysite/principal/templates/principal/index.html
<html>
    <head>
        <title>Principal</title>
        {% load static %}
        <link rel="stylesheet" href="{% static 'principal/index.css' %}">

    </head>
    <body>
        <header>
            <nav>
                <div id="botao-nav">Meus projetos</div>
            </nav>
        </header>
        <section class="container">
            <div class="sobre-esq">
                <h1 class="titulo">SOBRE MIM</h1>
                <br>
                <p class="texto"> Me chamo Bruno Lins dos Santos Viana e atualmente estou fazendo o curso de Tecnologia em Análise e Desenvolvimento de Sistemas pelo Instituto Federal de Educação, Ciência e Tecnologia do Rio Grande do Norte.</p>
            </div>
            <div class="sobre-dir">
                <img id="foto" src="{% static 'imgs/principal/bruno_foto.jpg' %}">
            </div>
        </section>
        <section class="container">
            <div class="container-esq">
                <a class="titulo" href="{% url 'enquetes:index' %}">Aplicação de Enquetes</a>
                <br>
            </div>
            <div class="container-dir">

            </div>
        </section>
        <section class="container">
            <div class="container-esq">
                <a class="titulo" href="{% url 'simulado:index' %}">Simulado</a>
                <br>
                <p class="texto">Projeto da disciplina de Desenvolvimento Web dedicado a criação de uma plataforma que permite o cadastro de usuários, questões, alternativas e simulados, além da funcionalidade de responde-los.</p>
            </div>
            <div class="container-dir">
                <img src="{% static 'imgs/principal/Flamengo.jpg' %}">

            </div>
        </section>
    </body>
</html>